# docker compose up --build
version: '3.7'
services:
  graphql-spring:
     build:
       context: . #DockerFile location 
       dockerfile: Dockerfile
     ports:
       - "8090:8090"
     restart: always
     depends_on:
       - mysql
     environment:
       # SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/OrderManagement
       SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/OrderManagement
       SPRING_DATASOURCE_USERNAME: OrderManagement_user
       SPRING_DATASOURCE_PASSWORD: OrderManagement_admin_password
       SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
       SERVER_PORT: 8090
       SERVER_HOST: 192.168.1.113
  mysql:
     image: mysql:8.0
     ports:
       - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
       MYSQL_USER: OrderManagement_user
       MYSQL_PASSWORD: OrderManagement_admin_password
       MYSQL_DATABASE: OrderManagement
     volumes:
       - "/home/altug/Desktop/mySQLContainer/db:/var/lib/mysql"
# docker exec -it <Cont-Id> bash
# mysql -u root -p